/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2015-05-01 22:11:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package game;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.xml.crypto.Data;
import java.util.List;
import java.util.ArrayList;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;

public final class initiategame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("javax.xml.crypto.Data");
    _jspx_imports_classes.add("java.sql.DriverManager");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.Statement");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<link href=\"../../HTML/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"JavaScript:timedRefresh(6300);\">\r\n");
      out.write("  <div id=\"header\"> <a href=\"#\"><img src=\"../../HTML/images/games_logo_big.jpg\" alt=\"Awesome Game Builder\" title=\"Awesome Game Builder\" border=\"0\" /></a>\r\n");
      out.write("   \r\n");
      out.write("  <h1></h1>\r\n");
      out.write("  </div>\r\n");
      out.write("<div id=\"bodyfooterPan\">\r\n");
      out.write("   \r\n");
      out.write("  ");


  PreparedStatement  st =null;
  ResultSet result =null;
  
  Connection con=null;
  
  try
  {
	  Class.forName("com.mysql.jdbc.Driver");
	  con = DriverManager.getConnection("jdbc:mysql://localhost:3306/isa681",
			  "ISA681", "World@123");
   st=con.prepareStatement("SELECT * from winstatistics where Id= ?");
   st.setInt(1, Integer.parseInt(""+session.getAttribute("userid")));
   result = st.executeQuery();
   result.next();
  out.println("<h2>Win/Loss Statistics</h2>");
  out.println("<br></br>");
  out.print("<table border=3>");
  out.print("<tr>");
  out.print("<th>Wins</th>");
  out.print("<th>Loses</th>");
  out.print("</tr>");
  out.print("<tr>");
  out.print("<td>");
  out.println(""+result.getInt(2));
  out.print("</td>");
  out.print("<td>");

  out.println(""+result.getInt(3));
  out.print("</td>");

  out.print("</tr>");
  out.print("</table>"); 

  out.println("<br></br>");
  
  out.println("<h1> Previous Game Moves</h1>");
  out.println("<br></br>");
  out.print("<table border=1>");
  out.print("<tr>");
  out.print("<th>Previous Games</th>");
  out.print("<th>Moves Of Selected Game</th>");
  out.print("</tr>");
  out.print("<tr>");
  out.print("<td>");
  st=con.prepareStatement("select Id from userinfo where (FirstPlayer_Id=? or SecondPlayer_Id =? )and (Status!='Waiting' or Status!='Ready')");
  st.setInt(1, Integer.parseInt(""+session.getAttribute("userid")));
  st.setInt(2, Integer.parseInt(""+session.getAttribute("userid")));
  result=st.executeQuery();
  out.println("<form action=initiategame.jsp>");
  out.print("<select name=gameno size=1>");
 int m=1;
  while(result.next())
  {
	  out.print("<option value="+result.getInt(1)+">Game: "+ m+"</option>");
	  m++;
  }
  out.print("</select>");
  out.print("<input name =button type=submit value=RETRIVE>");
  out.print("</form>");
  out.print("</td>");
  out.print("<td>");
 
  if(request.getParameter("gameno") != null)
  {
	 out.print("<textarea readonly rows=10 cols=50>");
	 st=con.prepareStatement("SELECT Moves FROM userinfo where Id = ?");
	 st.setInt(1, Integer.parseInt(""+request.getParameter("gameno")));
	 result = st.executeQuery();
	 result.next();
	 String words [] = result.getString(1).split("&");
	   for(int len =0; len<words.length;len++)
	   {
	   
	   out.print(""+words[len]);
	   out.print("\n");
	   }
	   out.print("</textarea>");
  }
  else
	  out.print(""+"Select Game for which moves to be displayed");
	  
  out.print("</td>");
  
  out.print("</table>");
  out.println("<br></br>");
  
  out.print("<table border=3>");
  out.print("<tr>");
  
  out.print("<th>Existing Game information</th>");
  out.print("<th>Click to join the gamezone</th>");
  out.print("</tr>");
  
  while(result.next())
 {
	 out.println(""+result.getString(1));
 }
 
  
  out.println("<h1> Join the existing game</h1>");
  out.println("<br></br>");

  
  ResultSet rs1;
 
  result = st.executeQuery("SELECT FirstPlayer_Id, SecondPlayer_Id FROM userinfo where Status='Waiting'");
  result.last();
  int k = result.getRow();
  int games[][] = new int [k][2];
  result.first();
    int i=0;
  while (i<k)
   {
       games[i][0]=result.getInt(1);
       games[i][1]=result.getInt(2);
       i++;
       result.next();
   }
    result.close();
int temp=0;

    while(temp<i)
    {
       int l=0;
        out.println("<tr>");
        out.println("<td>");
        st=con.prepareStatement("select user_name from usersrecord where Id=?");
        st.setInt(1, games[temp][0]);
        rs1= st.executeQuery();
        rs1.next();
        out.println("Game hosted by : "+rs1.getString(1));
        l++;
        out.println("<br></br>");
        rs1.close();
        if(games[temp][1]!=0)
        {
        st=con.prepareStatement("select user_name from usersrecord where Id=?");
        st.setInt(1, games[temp][1]);
        rs1= st.executeQuery();
        rs1.next();
        out.println("Game member:"+rs1.getString(1));
        out.println("<br></br>");
        l++;
        rs1.close();
        }    
        
      out.println("Current players: "+l);
    
       out.println("</td>");
       out.println("<td>");
    if(l<2)	   
    out.println("<form action=playgame.jsp method=post> <input type=hidden name=gameid value="+games[temp][0]+">  <input name =button type=submit value=JOIN> </input></form>");
       out.println("</td>");
     out.println("</tr>");
     temp++;
    }
  }
  catch( SQLException e ) 
  { 
      out.println(e.getMessage()); 
  } 
  finally
  { 
    /*   try
      { 
          if (con != null) 
              con.close (); 
          if (result != null) 
        	  result.close (); 
      } 
      catch (SQLException se) 
      { 
          out.println(se.getMessage()); 
      }  */
  } 
  
      out.write("\r\n");
      out.write("    <form action=\"playgame.jsp\" method=\"post\"> <input name =\"button\" type=\"submit\" value=\"NEW GAME..!!\"> </input></form>\r\n");
      out.write("<br />\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("<br></br>\r\n");
      out.write("<br></br>\r\n");
      out.write("<div>\r\n");
      out.write("  <form  action=\"endgame.jsp\" target=\"_top\" > \r\n");
      out.write("\t     <input name =\"button\" type=\"submit\" value=\"LOgOut\" /> \r\n");
      out.write("\t </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
